config/routes.rb
Rails.application.routes.draw do
  get '/home', to: 'pages#home', as: 'home'

  get '/about_us', to: 'pages#about', as: 'about'

  get 'lizard/:number', to: 'pages#lizards', as: 'lizards', number:/\d+/
  
  get 'winners', to: 'winners#winners', as: 'winners'

  get 'winner/:id', to: 'winners#winner', as: 'winner', id:/\d+/

  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/winner.rb
class Winner < ApplicationRecord
  validates :name, :length => { :minimum => 5 }, :presence => true
  validates :age, :numericality => true, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def lizards
    @number_of_lizards = params[:number].to_i
  end
end

app/controllers/winners_controller.rb
class WinnersController < ApplicationController
  def winners
    @winners = Winner.all
  end
  def winner
    @single = Winner.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/winners_helper.rb
module WinnersHelper
end

app/views/common/_header.html.erb
<header>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', about_url %></li>
    <li><%= link_to 'Winner', winners_path %></li>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KyleChallange</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'common/header'%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h2>About</h2>
<p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
  Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
  Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>

app/views/pages/home.html.erb
<h1>Home</h1>

<ul>
  <li><%= link_to '12', lizards_path(12) %></li>
  <li><%= link_to '444', lizards_path(444) %></li>
  <li><%= link_to '9672', lizards_path(9672)%></li>
</ul>
<p>Duis condimentum ipsum vel congue imperdiet. Ut convallis euismod elit, sed dignissim
  dui ornare quis. Quisque faucibus facilisis ornare. Etiam magna dolor, interdum in turpis
   sit amet, ultrices tincidunt nunc. Praesent sit amet erat fermentum, ornare mi sed, dignissim
    augue. Suspendisse venenatis sit amet urna non ornare. Orci varius natoque penatibus et magnis
     dis parturient montes, nascetur ridiculus mus.
   </p>

app/views/pages/lizards.html.erb
<h1><%= @number_of_lizards %> lizards</h1>

<% @number_of_lizards.times do%>
  🦎
<% end %>

app/views/winners/_winner.html.erb
<div class="winner"
  <p>
    <strong>NAME: </strong>
    <% if single_winner %>
      <%= link_to winner.name, winner_path(winner) %>
    <% else %>
      <%= winner.name %>
    <% end %>
    <strong>AGE: </strong><%= winner.age %>
  </p>
</div>

app/views/winners/winner.html.erb
<h2>Particular Winner</h2>

<%= render partial: 'winner',
           object: @single,
           locals: {single_winner: false} %>

<p><%= link_to 'Back', winners_path %></p>

app/views/winners/winners.html.erb
<h2>All Winners</h2>

<%= render partial: 'winner',
           collection: @winners,
           locals: {single_winner: true} %>